#pragma once
// This file has been generated by zoltan (https://github.com/jac3km4/zoltan)

#define ZOLTAN_STRINGISE(N) #N
#define ZOLTAN_EXPAND_THEN_STRINGISE(N) ZOLTAN_STRINGISE(N)
#define __LINE_STR__ ZOLTAN_EXPAND_THEN_STRINGISE(__LINE__)

#define Addresses_CBaseFunction_ExecuteNative_Addr 0x1FC191C
#define Addresses_CBaseFunction_ExecuteScripted_Addr 0x1874F0
#define Addresses_CBaseFunction_Handlers_Addr 0x32BEEB0
#define Addresses_CBaseFunction_InternalExecute_Addr 0x2E9C70
#define Addresses_CBaseRTTIType_sub_80_Addr 0x1FC15AC
#define Addresses_CBaseRTTIType_sub_88_Addr 0x1FC150C
#define Addresses_CBaseRTTIType_sub_90_Addr 0x1FC13E8
#define Addresses_CBaseRTTIType_sub_98_Addr 0x1FC1638
#define Addresses_CBaseRTTIType_sub_A0_Addr 0x1FC13D0
#define Addresses_CBitfield_FromString_Addr 0x1FD1E44
#define Addresses_CBitfield_ToString_Addr 0x1FD1F5C
#define Addresses_CBitfield_Unserialize_Addr 0x1BD1C4
#define Addresses_CClassFunction_ctor_Addr 0xA4E4A8
#define Addresses_CClassStaticFunction_ctor_Addr 0xA4E43C
#define Addresses_CClass_AssignDefaultValuesToProperties_Addr 0x15A168
#define Addresses_CClass_ClearScriptedData_Addr 0x5844B8
#define Addresses_CClass_CreateInstance_Addr 0x159FD0
#define Addresses_CClass_GetMaxAlignment_Addr 0x583664
#define Addresses_CClass_GetProperties_Addr 0x47DB70
#define Addresses_CClass_GetProperty_Addr 0x15AF58
#define Addresses_CClass_InitializeProperties_Addr 0x15A894
#define Addresses_CClass_ToString_Addr 0x845CA8
#define Addresses_CClass_Unserialize_Addr 0x15A654
#define Addresses_CClass_sub_80_Addr 0x1FBFEA8
#define Addresses_CClass_sub_88_Addr 0x1FBFDFC
#define Addresses_CClass_sub_90_Addr 0xB27B88
#define Addresses_CClass_sub_98_Addr 0x1FC1084
#define Addresses_CClass_sub_A0_Addr 0x1FC06B8
#define Addresses_CClass_sub_B0_Addr 0x8F5524
#define Addresses_CClass_sub_C0_Addr 0x4DD0B4
#define Addresses_CClass_sub_D0_Addr 0x1FC0D54
#define Addresses_CEnum_FromString_Addr 0x6D960C
#define Addresses_CEnum_ToString_Addr 0x6D7054
#define Addresses_CEnum_Unserialize_Addr 0x15B344
#define Addresses_CGameEngine_Addr 0x3302BF0
#define Addresses_CGlobalFunction_ctor_Addr 0xA4E3F0
#define Addresses_CNamePool_AddCString_Addr 0x217BF14
#define Addresses_CNamePool_AddCstr_Addr 0x21FD98
#define Addresses_CNamePool_AddPair_Addr 0x2F471C
#define Addresses_CNamePool_Get_Addr 0x1A11CC
#define Addresses_CRTTIRegistrator_Add_Addr 0x873030
#define Addresses_CRTTIRegistrator_RTTIAsyncId_Addr 0x3E3CB8C
#define Addresses_CRTTIScriptReferenceType_Set_Addr 0x2EAB7C
#define Addresses_CRTTIScriptReferenceType_ctor_Addr 0x180724
#define Addresses_CRTTISystem_Get_Addr 0x224838
#define Addresses_CStack_vtbl_Addr 0x2A860F0
#define Addresses_CString_copy_Addr 0x20348C
#define Addresses_CString_ctor_span_Addr 0x3034D8
#define Addresses_CString_ctor_str_Addr 0x217E88
#define Addresses_CString_dtor_Addr 0x158014
#define Addresses_DynArray_Realloc_Addr 0x1627E8
#define Addresses_Handle_DecWeakRef_Addr 0x15E808
#define Addresses_Handle_ctor_Addr 0x1588C0
#define Addresses_IScriptable_DestructValueHolder_Addr 0x15BEC0
#define Addresses_IScriptable_sub_D8_Addr 0x1FBAE98
#define Addresses_ISerializable_sub_30_Addr 0x1FADB34
#define Addresses_ISerializable_sub_40_Addr 0x15B5B4
#define Addresses_ISerializable_sub_78_Addr 0x93D174
#define Addresses_ISerializable_sub_A0_Addr 0x442A28
#define Addresses_ISerializable_sub_C0_Addr 0x49137C
#define Addresses_JobDispatcher_Addr 0x3310640
#define Addresses_JobDispatcher_DispatchJob_Addr 0x164DB0
#define Addresses_JobHandle_Join_Addr 0x164594
#define Addresses_JobHandle_ctor_Addr 0x166838
#define Addresses_JobHandle_dtor_Addr 0x166220
#define Addresses_JobQueue_Capture_Addr 0x1B99C8
#define Addresses_JobQueue_SyncWait_Addr 0x164F34
#define Addresses_JobQueue_ctor_FromGroup_Addr 0x166738
#define Addresses_JobQueue_ctor_FromParams_Addr 0x166778
#define Addresses_JobQueue_dtor_Addr 0x1644BC
#define Addresses_Memory_PoolStorage_OOM_Addr 0x1FA9194
#define Addresses_Memory_Vault_Addr 0x33107C0
#define Addresses_Memory_Vault_Alloc_Addr 0x1589C8
#define Addresses_Memory_Vault_AllocAligned_Addr 0x15DF5C
#define Addresses_Memory_Vault_Free_Addr 0x15E87C
#define Addresses_Memory_Vault_Realloc_Addr 0x6ADFF8
#define Addresses_Memory_Vault_ReallocAligned_Addr 0x164764
#define Addresses_Memory_Vault_Unk1_Addr 0x1FA9390
#define Addresses_OpcodeHandlers_Addr 0x327EEB0
#define Addresses_ResourceDepot_Addr 0x4773B18
#define Addresses_ResourceLoader_Addr 0x32FEEB8
#define Addresses_ResourceLoader_FindTokenFast_Addr 0x15F598
#define Addresses_ResourceLoader_LoadAsync_Addr 0x694794
#define Addresses_ResourceReference_Fetch_Addr 0x148914
#define Addresses_ResourceReference_Load_Addr 0x148940
#define Addresses_ResourceReference_Reset_Addr 0x33D624
#define Addresses_ResourceToken_CancelUnk38_Addr 0x2BF29C
#define Addresses_ResourceToken_DestructUnk38_Addr 0x21F278
#define Addresses_ResourceToken_Fetch_Addr 0x8B4064
#define Addresses_ResourceToken_OnLoaded_Addr 0x473E64
#define Addresses_ResourceToken_dtor_Addr 0x211504
#define Addresses_TTypedClass_IsEqual_Addr 0x22E11C
#define Addresses_TweakDB_CreateRecord_Addr 0x20B8C0
#define Addresses_TweakDB_Get_Addr 0x209DD4
#define Addresses_UpdateRegistrar_RegisterBucketUpdate_Addr 0x85A7E8
#define Addresses_UpdateRegistrar_RegisterGroupUpdate_Addr 0x85A938
#define CBaseRTTIType_VFT_Addr 0x2F68A08
#define CClass_VFT_Addr 0x2A1C9A8
#define ISerializable_VFT_Addr 0x2B08630
#define REUSED_Break_Addr 0x17CF7C8
#define REUSED_ReturnOne_Addr 0x187B259
#define REUSED_ReturnOne64_Addr 0x17ACA50
#define REUSED_ReturnZero_Addr 0x1814DB0
#define REUSED_ReturnZero64_Addr 0x17A47A0
#define REUSED_ReturnZero8_Addr 0x1807240
#define UpdateManagerUpdateStorage_Copy_0_Addr 0x85A648
#define audioGameParameterStorage_GetValue_Addr 0x1BD0C0
#define entComponentsStorage_GetSize_Addr 0x17B2250
#define entIComponent_VFT_Addr 0x2AE1530
#define gameIGameSystem_VFT_Addr 0x2C3B6A8
#define physicsProxyCache_GetDataFromCache_Addr 0x1F97E4
#define physicsVehiclePhysicsInsert1_SinMath_Addr 0x24917C
#define userRuntimeSettingsVarBool_VFT_Addr 0x30F0F18
#define userRuntimeSettingsVarFloatList_VFT_Addr 0x30F1B40
#define userRuntimeSettingsVarFloat_VFT_Addr 0x30F1AE8
#define userRuntimeSettingsVarInt_VFT_Addr 0x30F1A90
#define userRuntimeSettingsVarNameList_VFT_Addr 0x30F1020
#define userRuntimeSettingsVarName_VFT_Addr 0x30F0F70
#define userRuntimeSettingsVarStringList_VFT_Addr 0x2FCD188
#define userRuntimeSettingsVar_VFT_Addr 0x2FCD130
#define vehicleBikePhysics_VFT_Addr 0x300D3FE
#define vehiclePhysics_SetUnkA0ToOne_Addr 0x374D72
#define vehiclePhysics_VFT_Addr 0x300D128
#define vehicleTankPhysics_VFT_Addr 0x300D100
#define vehicleWheeledPhysics_VFT_Addr 0x300CE38

#include <RED4ext/RED4ext.hpp>
#include <RED4ext/Relocation.hpp>
#include <RED4ext/Addresses.hpp>
#include <RED4ext/RTTITypes.hpp>
#include <RED4ext/ISerializable.hpp>
#include <RED4ext/CommonFunctions.hpp>
#include <RED4ext/Scripting/Natives/UpdateManager.hpp>
#include <RED4ext/Scripting/Natives/audioEmitter.hpp>
#include <RED4ext/Scripting/Natives/entComponentsStorage.hpp>
#include <RED4ext/Scripting/Natives/entIComponent.hpp>
#include <RED4ext/Scripting/Natives/gameIGameSystem.hpp>
#include <RED4ext/Scripting/Natives/physicsProxyCache.hpp>
#include <RED4ext/Scripting/Natives/vehiclePhysicsInsert1.hpp>
#include <RED4ext/Scripting/Natives/userRuntimeSettingsVar.hpp>
#include <RED4ext/Scripting/Natives/vehiclePhysics.hpp>

RED4EXT_INLINE RED4ext::UpdateManager::UpdateStorage* RED4ext::UpdateManager::UpdateStorage::Copy_0(RED4ext::UpdateManager::UpdateStorage* a1) {
    using UpdateManagerUpdateStorage_Copy_0_t = RED4ext::UpdateManager::UpdateStorage* (*)(RED4ext::UpdateManager::UpdateStorage*, RED4ext::UpdateManager::UpdateStorage*);
    RED4ext::RelocFunc<UpdateManagerUpdateStorage_Copy_0_t> call(UpdateManagerUpdateStorage_Copy_0_Addr);
    return call(this, a1);
}

RED4EXT_INLINE float RED4ext::audio::GameParameterStorage::GetValue(RED4ext::CName a1, float a2) {
    using audioGameParameterStorage_GetValue_t = float (*)(RED4ext::audio::GameParameterStorage*, RED4ext::CName, float);
    RED4ext::RelocFunc<audioGameParameterStorage_GetValue_t> call(audioGameParameterStorage_GetValue_Addr);
    return call(this, a1, a2);
}

RED4EXT_INLINE int64_t RED4ext::ent::ComponentsStorage::GetSize() {
    using entComponentsStorage_GetSize_t = int64_t (*)(RED4ext::ent::ComponentsStorage*);
    RED4ext::RelocFunc<entComponentsStorage_GetSize_t> call(entComponentsStorage_GetSize_Addr);
    return call(this);
}

RED4EXT_INLINE void* RED4ext::physics::ProxyCache::GetDataFromCache(uint32_t a1) {
    using physicsProxyCache_GetDataFromCache_t = void* (*)(RED4ext::physics::ProxyCache*, uint32_t);
    RED4ext::RelocFunc<physicsProxyCache_GetDataFromCache_t> call(physicsProxyCache_GetDataFromCache_Addr);
    return call(this, a1);
}

RED4EXT_INLINE float RED4ext::physics::VehiclePhysicsInsert1::SinMath(float a1) {
    using physicsVehiclePhysicsInsert1_SinMath_t = float (*)(RED4ext::physics::VehiclePhysicsInsert1*, float);
    RED4ext::RelocFunc<physicsVehiclePhysicsInsert1_SinMath_t> call(physicsVehiclePhysicsInsert1_SinMath_Addr);
    return call(this, a1);
}

RED4EXT_INLINE void RED4ext::vehicle::Physics::SetUnkA0ToOne() {
    using vehiclePhysics_SetUnkA0ToOne_t = void (*)(RED4ext::vehicle::Physics*);
    RED4ext::RelocFunc<vehiclePhysics_SetUnkA0ToOne_t> call(vehiclePhysics_SetUnkA0ToOne_Addr);
    return call(this);
}

