#pragma once

// This file is generated by Jack

#include <cstdint>
#include <RED4ext/Common.hpp>
#include <RED4ext/Scripting/IScriptable.hpp>

namespace RED4ext
{
namespace world { 

// also used by gameGameSessionDesc
struct RuntimeDescription
{
    // 1.52 RVA: 0xB508B0 / 11864240
    /// @pattern 40 53 48 83 EC 20 33 C0 48 8B D9 48 89 01 48 89 41 08 48 83 C1 10 E8 75 FB 64 FF 48 8D 4B 30 E8
    RuntimeDescription();

    // 0x6B19682BA3D859CF - cname? resource?
    CName unk00;
    // set to base\worlds\03_night_city\_compiled\default\03_night_city.streamingworld somewhere
    ResourcePath streamingWorld;
    // set to "03_night_city"
    CString str;
    // 0x445666BF489EC042
    ResourceAsyncReference resource;
};

struct RuntimeInfo : IScriptable
{
    static constexpr const char* NAME = "worldRuntimeInfo";
    static constexpr const char* ALIAS = "RuntimeInfo";

    enum class Mode : byte {
        Unknown = 0x0,
        Singleplayer = 0x1,
        MultiplayerClient = 0x2,
        MultiplayerServer = 0x3
    };

    virtual CClass * __fastcall GetNativeType() override;

    Mode mode;
    uint8_t unk41;
    uint8_t unk42[6];
    RuntimeDescription description;
};
} // namespace world
using RuntimeInfo = world::RuntimeInfo;
} // namespace RED4ext
