#pragma once

// This file is generated by Jack

#include <cstdint>
#include <RED4ext/Common.hpp>

namespace RED4ext {
namespace action {

struct MovementController
{
  virtual uint64_t GetSystem();
  virtual void __MovementController();
  virtual void sub_10();
  virtual void sub_18();
  virtual void sub_20();
  virtual void sub_28();
  virtual void sub_30();
  virtual void sub_38();
  virtual void sub_40();
  virtual void sub_48();
  virtual void GetTypeName();
  virtual void sub_58();
  virtual void sub_60();
  virtual void sub_68();
  virtual void sub_70(uint64_t, uint64_t);
  virtual void sub_78();
  virtual void sub_80();

  uint32_t unk08;
  uint32_t unk0C;
  uint64_t unk10;
  uint64_t unk18;
  uint8_t unk20;
};


struct SlideTo : ActionBase
{
  uint64_t unk50;
  MovementController movementController;
  uint64_t unk80;
  uint64_t unk88;
  float unk90;
  float unk94;
  float unk98;
  float unk9C;
  uint64_t unkA0;
  uint64_t unkA8;
  uint64_t unkB0;
  uint16_t unkB8;
};

} // namespace action
} // namespace RED4ext