#pragma once

// This file is generated by Jack

#include <cstdint>
#include <RED4ext/Common.hpp>
#include <RED4ext/Scripting/Natives/vehicleBaseObject.hpp>

namespace RED4ext
{
struct ActionInterface {
    virtual void * Destruct(char);

    // 1.52 RVA: 0x1B21550 / 28448080
    /// @pattern 48 89 5C 24 08 48 89 74 24 10 57 48 83 EC 20 48 8B F9 48 8B F2 48 81 C1 EA 00 00 00 E8 AF 9E 01
    uint8_t __fastcall AddItem(void *);

    // 1.52 RVA: 0x1B216C0 / 28448448
    /// @pattern 48 89 5C 24 10 57 48 83 EC 30 48 8B 41 58 48 8B FA 48 8B 98 28 02 00 00 E8 43 E4 AB FF 4C 8B 03
    Handle<void> *__fastcall GetActionsFactory(Handle<void> *);

    DynArray<void*> unk08;
    uint64_t unk18;
    uint32_t handleCount;
    uint32_t unk24;
    uint64_t unk28;
    uint64_t unk30[4];
    uint64_t unk50;
    vehicle::BaseObject *thisVehicle;
    vehicle::BaseObject *unk60[16];
    uint32_t unk60count;
    uint32_t unkE4;
    SharedMutex unk08Mutex;
    SharedMutex mutex2;
    SharedMutex unk60Mutex;
    uint8_t unkEB;
    uint32_t unkEC;
};
RED4EXT_ASSERT_SIZE(ActionInterface, 0xF0);
} // namespace RED4ext
