#pragma once

// This file is generated by Jack

#include <RED4ext/Common.hpp>
#include <cstdint>
#include <RED4ext/Scripting/Natives/Generated/ent/EntityInstanceData.hpp>
#include <RED4ext/ResourcePath.hpp>

namespace RED4ext
{
namespace ent
{
struct IComponent;
struct EntityDefinition
{
    static constexpr const char* NAME = "entEntityDefinition";
    static constexpr const char* ALIAS = "EntityDefinition";

    ResourcePath resource;
    CName appearance;
    uint64_t unk10;
    DynArray<EntityInstanceData> unk18;
    void* unk28;
    uint64_t unk30;
    void* unk38;
    void* unk40;
    uint32_t unk48;
    uint32_t unk4C;
    DynArray<Handle<IComponent>> components;
    DynArray<void*> effects;
};
RED4EXT_ASSERT_SIZE(EntityDefinition, 0x70);
} // namespace ent
} // namespace RED4ext
