#pragma once

// This file is generated by Jack

#include <cstdint>
#include <RED4ext/Common.hpp>
#include <RED4ext/Scripting/Natives/Generated/WorldTransform.hpp>
#include <RED4ext/Scripting/Natives/Generated/Transform.hpp>

namespace RED4ext::ent {

struct ITransformAttachable {

    /// @pattern 44 65 63 6F 72 61 74 69 6F 6E 4E 6F 64 65 00 00 FF FF FF FF FF FF FF FF FF FF FF FF 00 00 00 00
    /// @offset -16
    static constexpr const uintptr_t VFT = 0;

    virtual ~ITransformAttachable();
    // called from OnSimulate_PushDirtyTransformData when flags & 0x40 or unk38 == 2
    // WT & bool comes from unk1A2018 - Transform is empty
    virtual void ITransformAttachable_08(WorldTransform *, bool, Transform*);
    // empty for many implementations
    // called with idStorage.unk00, unk24 and unk28 from Physics/KickAndWaitSimulation/NotifyListeners
    virtual void ITransformAttachable_10(uint64_t, uint32_t, uint32_t);
};

}