#pragma once

// This file is generated by Jack

#include <cstdint>
#include <RED4ext/Common.hpp>
#include <RED4ext/Scripting/IScriptable.hpp>
#include <RED4ext/Scripting/Natives/IUpdatableSystem.hpp>

namespace RED4ext
{
namespace game { 
// mabe this instead?
// struct IGameSystem : IScriptable, virtual IUpdatableSystem
struct IGameSystem : IUpdatableSystem
{
    static constexpr const char* NAME = "gameIGameSystem";
    static constexpr const char* ALIAS = "IGameSystem";
    static constexpr const uintptr_t VFT_RVA = 0x31B53F0;

    struct HighLow
    {
        void *unk00;
        void *unk08;
        uint8_t unk10;
    };

    // 1.52 RVA: 0xAEC190 / 11452816
    /// @pattern 40 53 48 83 EC 20 48 8B D9 E8 22 B8 F8 FF 48 8D 05 4B 92 6C 02 48 C7 43 40 00 00 00 00 48 89 03
    //IGameSystem();

    virtual CClass* GetNativeType() override;     
    virtual ~IGameSystem() override = default;

    virtual bool sub_118(void *); // 108 onAttach
    virtual void sub_120(void * runtimeScene); // 120 onDetach
    virtual void sub_128(void * runtimeScene); // 128 Setup
    virtual void sub_130(); // 130
    virtual void sub_138(); // AK::MemoryMgr::StopProfileThreadUsage(void)
    virtual void sub_140(); // 140
    virtual void sub_148(); // 148
    // 150, OnGameLoad
    virtual void sub_150(void *, uint64_t, uint64_t); 
    // ReturnOne - should probably always return 1
    virtual bool sub_158();
    virtual void sub_160(); // 160
    // might be called from GameInstance->Systems168o170
    virtual void sub_168(); // 168
    // might be called from GameInstance->Systems168o170
    virtual void sub_170(); // 170
    // something with a CString @ 0x08
    virtual void sub_178(uintptr_t a1, bool a2);                    
    virtual void sub_180(uint64_t, bool isGameLoaded, uint64_t); // 180
    virtual void sub_188(); // 188
    // called from GameInstance->sub_20
    virtual void sub_190(HighLow *); // 190
    // some systems load tweaks - might be a setup, called from GameInstance->sub_20
    virtual void sub_198(void *); // 198
    virtual void sub_1A0(); // 1A0

    // 1.52 RVA: 0xAEC8E0 / 11454688
    // Sets unk40, calls sub_198
    /// @pattern 48 89 5C 24 10 57 48 83 EC 20 48 8B FA 66 C7 44 24 30 00 00 0F B7 44 24 30 48 8D 54 24 30 4C 89
    void * __fastcall Set(void *, void * unk40);

    // 1.52 RVA: 0xAEC970 / 11454832
    // Unsets unk40, calls sub_1A0
    /// @pattern 40 53 48 83 EC 20 48 8B 01 48 8B D9 FF 90 A0 01 00 00 48 C7 43 40 00 00 00 00 48 83 C4 20 5B C3
    __int64 __fastcall Unset();

    uint8_t unk40[0x48 - 0x40]; // 40
};
RED4EXT_ASSERT_SIZE(IGameSystem, 0x48);
} // namespace game
} // namespace RED4ext

#ifdef RED4EXT_HEADER_ONLY
#include <RED4ext/Scripting/Natives/gameIGameSystem-inl.hpp>
#endif
