#pragma once

// This file is generated by Jack

#include <cstdint>
#include <RED4ext/Common.hpp>
#include <RED4ext/Addresses-Found.hpp>

namespace RED4ext::physics {

struct BaseSystemKey;

struct GeoCacheID {
    // 1.6 RVA: 0x448BD0 / 4492240
    /// @pattern 4C 8B DC 53 56 48 83 EC 68 8B 01 48 8B D9 49 8D 4B 08 41 89 43 08 48 8B F2 E8 52 25 02 00 48 85
    bool __fastcall Unk(void *a2);

    // 1.6 RVA: 0x46AC90 / 4631696
    /// @pattern 48 89 5C 24 10 57 48 83 EC 20 8B 01 48 8B FA 48 8B D9 89 44 24 30 48 8B 0D FB 4D D1 03 48 8D 54
    bool __fastcall Something2(__int64 a2);

    // only used by types 2, 3, 5, 6, 10, 12, 13
    // 1.6  RVA: 0x46B140 / 4632896
    // 1.62 RVA: 0x46BA70 / 4635248
    /// @pattern 40 53 48 83 EC 30 8B 01 4C 8D 44 24 40 48 8B 0D ? ? D1 03 48 8D 54 24 20 89 44 24 40 E8 AE F2
    inline BaseSystemKey *__fastcall GetSystemKey() {
      RelocFunc<decltype(&GeoCacheID::GetSystemKey)> call(physicsGeoCacheID_GetSystemKey_Addr);
      return call(this);
    } 

    uint32_t id;
};

struct GeoCacheStuff
{
  SharedMutex unk00;
  Handle<void*> unk08;
  Handle<void*> unk18;
  uint32_t unk28;
  uint32_t unk2C;
  uint64_t unk30;
  uint64_t unk38;
  uint64_t unk40[31];
  uint32_t unk138;
  uint32_t unk13C;
  // index'd by unk2A2054
  uint64_t unk140[256];
  uint32_t unk940;
  uint32_t unk944;
  uint32_t unk948;
  uint32_t unk94C;
  uint64_t unk950[255];
  uint32_t unk1148;
  uint32_t unk114C;
};

struct GeoKeyStorage {
    // 1.6 RVA: 0x46A7E0 / 4630496
    /// @pattern 48 89 74 24 10 57 48 83 EC 20 44 8B 02 48 8B F2 48 8B F9 41 83 F8 FF 74 67 B8 FF FF 00 00 66 44
    bool __fastcall TestUnk2E2068(GeoCacheID *p_geoCacheID);

    SharedMutex unk0000;
    uint64_t unk0008[1023];
    uint32_t unk2000;
    uint32_t unk2004;
    uint32_t unk2008;
    uint32_t unk200C;
    uint32_t unk2010;
    // index'd by GeoCacheID - Handle to physics::PhysicalSystemKey
    Handle<BaseSystemKey> unk2014[65535];
    uint32_t unk102008;
    uint32_t unk10200C;
    // index'd by GeoCacheID
    uint16_t unk102010[65536];
    uint16_t unk122010;
    uint16_t unk122012;
    uint16_t unk122014;
    uint16_t unk122016;
    // index'd by GeoCacheID
    uint64_t unk122018[65535];
    uint32_t unk1A2010;
    // index'd by GeoCacheID - phyicsSystemDesc->unkA0
    uint64_t unk1A2018[65535];
    uint32_t unk222010;
    // index'd by GeoCacheID - physicsSystemDesc->unkA8 / ChassisComponent's unk120/interface
    uint64_t unk222018[65535];
    uint32_t unk2A2010;
    uint32_t unk2A2014;
    // physicsSystemDesc types
    uint32_t refCounts_2A2018[15];
    // index'd by GeoCacheID
    uint32_t unk2A2054[32753];
    uint64_t unk2C2018[16384];
    uint32_t unk2E2018[14];
    uint32_t unk2E2050;
    // mutex for unk2E2058 
    SharedMutex unk2E2054;
    DynArray<void*> unk2E2058;
    // index'd by GeoCacheID >> 5
    int unk2E2068[2048];
};

}