#pragma once

// clang-format off

// This file is generated by Jack

#include <cstdint>
#include <RED4ext/Common.hpp>

namespace RED4ext::physics {

enum class ProxyType : uint8_t {
    Invalid = 0,
    PhysicalSystem = 1,
    CharacterController = 2,
    Destruction = 3,
    ParticleSystem = 4,
    Trigger = 5,
    Cloth = 6,
    WorldCollision = 7,
    Terrain = 8,
    SimpleCollider = 9,
    AggregateSystem = 10,
    CharacterObstacle = 11,
    Ragdoll = 12,
    FoliageDestruction = 13
};

}