#pragma once

// clang-format off

// This file is generated by Jack

#include <cstdint>
#include <RED4ext/Common.hpp>
#include <RED4ext/Scripting/Natives/physicsProxyType.hpp>
#include <RED4ext/Scripting/Natives/physicsInitialState.hpp>
#include <RED4ext/Scripting/Natives/entITransformAttachable.hpp>
#include <RED4ext/Scripting/Natives/Generated/physics/SystemResource.hpp>

namespace RED4ext {
namespace ent { struct Entity; struct IComponent; }
namespace physics {
struct BaseProxyDesc
{
    // after "physicsGeometryKey" vft
    // 1.6  RVA: 0x313B3D0
    static constexpr const uintptr_t VFT = 0x313B3D0;

    // checks multiple things
    virtual bool CanAdd();
    virtual CString* GetName(CString*);
    virtual uint32_t GetMaxEntries();
    virtual uint8_t GetType();

    Handle<ent::Entity> entity;
    Handle<ent::IComponent> component;
    // num of handles used
    uint32_t numHandles;
    uint32_t unk2C;
    uint64_t unk30[6];
    uint64_t unk60[7];
    uint8_t unk98;
    // set with chassis.unk180, stored at GeoKeyStorage::unk1A2018
    NativeArrayInitialState, 32> * initialStates;
    ent::ITransformAttachable attachable;
    uint64_t unkB0;
    // 0x17 for chassis
    uint8_t unkB8;
    uint64_t unkC0[1];
    uint8_t isStatic;
    uint64_t unkD0[5];
    ProxyType type;
    HandleSystemResource> resource;
};
RED4EXT_ASSERT_OFFSET(ProxyDesc, resource, 0x100);
}
}