#pragma once

// clang-format off

// This file is generated by Jack

#include <cstdint>
#include <RED4ext/Common.hpp>
#include <RED4ext/Scripting/Natives/physicsProxyDesc.hpp>
#include <RED4ext/Scripting/Natives/Generated/physics/FilterData.hpp>
#include <RED4ext/Scripting/Natives/Generated/physics/SimulationType.hpp>

namespace RED4ext {
namespace physics {

struct PhysicalSystemDesc : ProxyDesc
{
    // after ProxyDesc's
    // 1.6  RVA: 0x313B3F0
    static constexpr const uintptr_t VFT = 0x313B3F0;
    physics::FilterData * filterDataStart;
    uint64_t unk118;
    WorldTransform unk120;
    WorldPosition unk140;
    // 0x1/Dynamic for chassis
    physics::SimulationType fallbackSimulationType;
    // 0x1 for chassis
    uint8_t unk14D;
    uint8_t unk14E;
    uint8_t unk14F;
    uint8_t enableSelfCollision;
    uint8_t hasSystemBodyParams;
};
}
}