#pragma once

// This file is generated by Jack

#include <cstdint>
#include <RED4ext/Common.hpp>
#include <RED4ext/Addresses-Found.hpp>
#include <RED4ext/Scripting/Natives/Generated/WorldTransform.hpp>

namespace RED4ext::physics {

struct CollisionInterface {
    virtual ~CollisionInterface();
    virtual void CollisionInterface_08(WorldTransform *, bool);
    virtual void CollisionInterface_10();
};

}