#pragma once

// This file is generated by Jack

#include <RED4ext/Common.hpp>
#include <cstdint>
#include <RED4ext/Scripting/Natives/physicsProxyID.hpp>

namespace RED4ext::physics {
struct ProxyCacheID {
    // 1.6  RVA: 0x4BA520 / 4957472
    /// @pattern 40 53 48 83 EC 20 8B 01 48 8B DA 48 8B 0D 7E 55 CC 03 48 8D 54 24 30 89 44 24 30 E8 E0 FF FA FF
    void __fastcall EnableCollision(ProxyID *proxyID);

    // 1.6  RVA: 0x4BA720 / 4957984
    /// @pattern 40 53 48 83 EC 20 8B 01 48 8B DA 48 8B 0D 7E 53 CC 03 48 8D 54 24 30 89 44 24 30 E8 E0 FD FA FF
    void __fastcall DisableCollision(ProxyID *proxyID);

    uint16_t index;
    uint16_t unk38_match;
};
}