#pragma once

// This file is generated by Jack

#include <cstdint>
#include <RED4ext/Common.hpp>
#include <RED4ext/Scripting/Natives/Generated/Transform.hpp>
#include <RED4ext/Scripting/Natives/Generated/Vector3.hpp>
#include <RED4ext/Scripting/Natives/Generated/FixedPoint.hpp>
#include <RED4ext/Scripting/Natives/Generated/vehicle/BaseObject.hpp>

namespace RED4ext
{
namespace physics { 
struct VehiclePhysicsInsert1
{
    static constexpr const char* NAME = "physicsVehiclePhysicsInsert1";
    static constexpr const char* ALIAS = NAME;

    RED4ext::Vector4 unk00;
    RED4ext::Vector4 unk10;
    RED4ext::Vector4 unk20;
    uint32_t unk30;
    RED4ext::Vector3 unk34;
    RED4ext::Quaternion unk40;
    void* physx3Thing1;
    uint64_t unk58;
    RED4ext::Vector4 unk60;
    RED4ext::Quaternion unk70;
    RED4ext::Vector4 unk80;
    RED4ext::Vector4 unk90;
    RED4ext::Vector4 unkA0;
    RED4ext::Vector4 unkB0;
    RED4ext::Vector4 unkC0;
    RED4ext::Vector4 unkD0;
    uint64_t unkE0;
    void* parent3;
    RED4ext::Handle<void> vehicleWheelDimensionsPreset;
    RED4ext::Handle<void> vehicleWheelDrivingPreset;
    RED4ext::Handle<void> vehicleWheelRolePreset;
    RED4ext::FixedPoint unk120;
    RED4ext::FixedPoint unk124;
    RED4ext::FixedPoint unk128;
    RED4ext::FixedPoint unk12C;
};
RED4EXT_ASSERT_SIZE(VehiclePhysicsInsert1, 0x130);
} // namespace physics
} // namespace RED4ext
