#pragma once

// This file is generated by Jack

#include <cstdint>
#include <RED4ext/Common.hpp>
#include <RED4ext/Scripting/Natives/Generated/Vector3.hpp>
#include <RED4ext/Scripting/Natives/Generated/vehicle/BaseObject.hpp>
#include <RED4ext/Scripting/Natives/vehicleAirControlAxis.hpp>

namespace RED4ext
{
namespace vehicle { 
struct BaseObject;

#pragma pack(push, 1)
struct AirControl
{
    static constexpr const char* NAME = "vehicleAirControl";
    static constexpr const char* ALIAS = NAME;

    BaseObject * vehicle;
    float unk08;
    AirControlAxis pitch;
    AirControlAxis yaw;
    AirControlAxis roll;
    Vector3 anglePID;
    Vector3 velocityPID;
    Vector3 flippedOverRecoveryPID;
    float massReference;
    float unk244;
};
#pragma pack(pop)
RED4EXT_ASSERT_SIZE(AirControl, 0x248);
} // namespace vehicle
} // namespace RED4ext
