#pragma once

// This file is generated by Jack

#include <cstdint>
#include <RED4ext/Common.hpp>

#include <RED4ext/Scripting/Natives/worldRuntimeInfo.hpp>
// #include <RED4ext/GameEngine.hpp>

namespace RED4ext
{
namespace world { 
struct IRuntimeSystem;
struct GameInstance;
struct RuntimeScene
{
    static constexpr const char* NAME = "worldRuntimeScene";
    static constexpr const char* ALIAS = NAME;

    struct Flags {
        bool inPreview;
        bool inSingleplayer;
        bool onClientWithVisuals;
        bool onClientWithoutVisuals;
        bool onHeadlessServerWithoutVisuals;
        bool onServer;
        bool RenderDebugInProfiling;
    };

    // 1.52 RVA: 0xB7BE60 / 12041824
    // calls SetupRuntimeSystems with new unkThing & a2
    /// @pattern 40 53 48 83 EC 60 41 8B 01 49 8B D8 85 C0 74 46 4C 8B C2 48 8D 94 24 88 00 00 00 E8 A0 FB FF FF
    uint32_t __fastcall SetupWithLogging(unsigned char *a2, __int64 a3, uint32_t *a4);

    // 1.52 RVA: 0xB7BA20 / 12040736
    // creates isystems from children of world::IRuntimeSystem, calls systems->sub_128, which returns an index for storage
    // looks at engine\systems\runtime_systems_startup.csv for the flags for each system
    // has a maximum 0x41/65 systems (58 exist in the .csv)
    // Loads all worldNode types, cnames & strings at the end
    /// @pattern 48 89 5C 24 18 48 89 54 24 10 55 56 57 41 54 41 55 41 56 41 57 48 8D 6C 24 D9 48 81 EC C0 00 00
    // void **__fastcall SetupRuntimeSystems(void **unkThing, unsigned char *a3);

    // 1.52 RVA: 0xB7BDE0 / 12041696
    // calls GameTools->sub_50, systems->sub_188
    /// @pattern 48 89 5C 24 08 57 48 83 EC 20 48 8B F9 48 8B 0D AC 20 34 03 48 85 C9 74 06 48 8B 01 FF 50 50 8B
    // __int64 __fastcall Systems188();

    // 1.52 RVA: 0xB7C130 / 12042544
    /// @pattern 40 57 48 83 EC 20 83 B9 10 04 00 00 00 48 8B F9 0F 84 B4 00 00 00 48 8B 89 A0 02 00 00 48 89 5C
    // __int64 __fastcall Systems190();

/*
 1 - In Preview
 2 - In Singleplayer
 3 - On Client (with visuals)
 4 - On Headless Client (without visuals)
 5 - On Headless Server (without visuals)
 6 - On Server (with visuals)
 7 - Run RenderDebug in Profiling

System Name                                    1  2  3  4  5  6  7
-------------------------------------------------------------------
FunctionalTestsRuntimeSystem                   x  x  x          
InternalFunctionalTestsRuntimeSystem           x  x  x          
netEntitySystem                                      x  x  x  x 
toolsRuntimeSystemPreviewSpawn                 x                
workWorkspotSystem                             x  x  x  x  x  x 
worldNodeInstanceRegistry                      x  x  x  x  x  x 
worldRuntimeEntityRegistry                     x  x  x  x  x  x 
worldAnimationSystem                           x  x  x  x  x  x 
worldCorpseSystem                              x  x  x  x  x  x 
worldRuntimeSystemAudio                        x  x  x        x 
worldRuntimeSystemBinkUpdate                   x  x  x        x 
worldRuntimeSystemCamera                       x                
worldRuntimeSystemDebugRendering               x  x  x        x 
worldRuntimeSystemDismemberment                x  x  x  x  x  x 
worldRuntimeSystemEffects                      x  x  x  x  x  x 
worldRuntimeSystemEffectAttachments            x  x  x        x 
worldRuntimeSystemEntity                       x  x  x  x  x  x 
worldRuntimeSystemDestruction                  x  x  x  x  x  x 
worldRuntimeSystemEntityAppearanceChanger      x  x  x  x  x  x 
worldRuntimeSystemEntityTransforms             x  x  x  x  x  x 
worldRuntimeSystemEnvironment                  x  x  x        x 
worldRuntimeSystemWeather                      x  x  x  x  x  x 
worldRuntimeSystemWeatherDebugging             x  x             
worldRuntimeSystemGI                           x                
worldRuntimeSystemInspector                    x  x  x        x 
worldRuntimeSystemMarkers                      x  x  x  x  x  x 
worldRuntimeSystemMoverComponents              x  x  x     x  x 
worldRuntimeSystemNavigation                   x  x  x  x  x  x 
worldRuntimeSystemNodeStreaming                x  x  x  x  x  x 
worldRuntimeSystemPhysics                      x  x  x  x  x  x 
worldRuntimeSystemPrefabInstancing             x                
worldRuntimeSystemRemoteViews                  x  x  x        x 
worldRuntimeSystemRendering                    x  x  x        x 
worldRuntimeSystemRepellerComponents           x  x  x  x  x  x 
worldRuntimeSystemScenes                       x  x  x     x  x 
worldRuntimeSystemSnapSovler                   x                
worldRuntimeSystemTerrain                      x                
worldRuntimeSystemCompiledTerrain              x                
worldRuntimeSystemTraffic                      x  x  x  x  x  x 
worldRuntimeSystemTransformAnimator            x  x  x  x  x  x 
worldRuntimeSystemTriggers                     x  x  x  x  x  x 
worldRuntimeSystemVisibility                   x  x  x        x 
worldRuntimeSystemWorldStreaming                  x  x  x  x  x  x 
worldRuntimeSystemStreamingQuery                  x  x  x  x  x 
worldgeometryRuntimeSystemGeomDescription      x  x  x  x  x  x 
worldRuntimeSystemMetrics                      x  x  x        x  x 
worldRuntimeSystemWorldDebugging               x  x  x        x 
worldRuntimeSystemSmartObjects                 x  x  x  x  x  x 
navRuntimeSystemPathfinding                    x  x  x  x  x  x 
worlduiRuntimeSystemUI                         x  x  x          
worldRuntimeSystemEntityTransactor             x  x  x  x  x  x 
worldRuntimeSystemSphereTreeGen                x  x             
gameRuntimeSystemLights                        x  x  x        x 
worldRuntimeSystemFoliage                      x  x  x          
worldRuntimeSystemEntityVisualController       x  x  x        x 
toolsBugFlagsSystem                            x  x  x          
debugRuntimeSystemSpeedSplinePreview           x                
entRuntimeSystemEditorMeshes                   x                
*/

    StaticArray<Handle<IRuntimeSystem>, 0x41> systems;
    GameInstance* gameInstance;
    uint64_t unk420;
    RuntimeInfo runtimeInfo;
    uint64_t unk4A8;
};
} // namespace world
} // namespace RED4ext
