find_program(POWERSHELL_PATH NAMES powershell
HINTS
  C:/Windows/System32/WindowsPowerShell/v1.0/
)

  # execute_process(COMMAND
  #   ${POWERSHELL_PATH} "(Get-Item '${CYBERPUNK_2077_GAME_DIR}/bin/x64/Cyberpunk2077.exe').VersionInfo.ProductVersionRaw.Major"
  #   OUTPUT_VARIABLE CYBERPUNK_2077_PRODUCT_VERSION_MAJOR OUTPUT_STRIP_TRAILING_WHITESPACE
  # )
  # execute_process(COMMAND
  #   ${POWERSHELL_PATH} "(Get-Item '${CYBERPUNK_2077_GAME_DIR}/bin/x64/Cyberpunk2077.exe').VersionInfo.ProductVersionRaw.Minor"
  #   OUTPUT_VARIABLE CYBERPUNK_2077_PRODUCT_VERSION_MINOR OUTPUT_STRIP_TRAILING_WHITESPACE
  # )
  # execute_process(COMMAND
  #   ${POWERSHELL_PATH} "(Get-Item '${CYBERPUNK_2077_GAME_DIR}/bin/x64/Cyberpunk2077.exe').VersionInfo.ProductVersionRaw.Build"
  #   OUTPUT_VARIABLE CYBERPUNK_2077_PRODUCT_VERSION_BUILD OUTPUT_STRIP_TRAILING_WHITESPACE
  # )
  # execute_process(COMMAND
  #   ${POWERSHELL_PATH} "(Get-Item '${CYBERPUNK_2077_GAME_DIR}/bin/x64/Cyberpunk2077.exe').VersionInfo.ProductVersionRaw.Revision"
  #   OUTPUT_VARIABLE CYBERPUNK_2077_PRODUCT_VERSION_REVISION OUTPUT_STRIP_TRAILING_WHITESPACE
  # )

  # set(CYBERPUNK_2077_PRODUCT_VERSION_STR ${CYBERPUNK_2077_PRODUCT_VERSION_MAJOR}.${CYBERPUNK_2077_PRODUCT_VERSION_MINOR}.${CYBERPUNK_2077_PRODUCT_VERSION_BUILD}.${CYBERPUNK_2077_PRODUCT_VERSION_REVISION})

  # message(STATUS "Game's ProductVersion: ${CYBERPUNK_2077_PRODUCT_VERSION_STR}")
if(EXISTS "${CYBERPUNK_2077_GAME_DIR}/bin/x64/Cyberpunk2077.exe")

  execute_process(COMMAND
    ${POWERSHELL_PATH} "(Get-Item '${CYBERPUNK_2077_GAME_DIR}/bin/x64/Cyberpunk2077.exe').VersionInfo.FileVersionRaw.Major"
    OUTPUT_VARIABLE CYBERPUNK_2077_FILE_VERSION_MAJOR OUTPUT_STRIP_TRAILING_WHITESPACE
  )
  execute_process(COMMAND
    ${POWERSHELL_PATH} "(Get-Item '${CYBERPUNK_2077_GAME_DIR}/bin/x64/Cyberpunk2077.exe').VersionInfo.FileVersionRaw.Minor"
    OUTPUT_VARIABLE CYBERPUNK_2077_FILE_VERSION_MINOR OUTPUT_STRIP_TRAILING_WHITESPACE
  )
  execute_process(COMMAND
    ${POWERSHELL_PATH} "(Get-Item '${CYBERPUNK_2077_GAME_DIR}/bin/x64/Cyberpunk2077.exe').VersionInfo.FileVersionRaw.Build"
    OUTPUT_VARIABLE CYBERPUNK_2077_FILE_VERSION_BUILD OUTPUT_STRIP_TRAILING_WHITESPACE
  )
  execute_process(COMMAND
    ${POWERSHELL_PATH} "(Get-Item '${CYBERPUNK_2077_GAME_DIR}/bin/x64/Cyberpunk2077.exe').VersionInfo.FileVersionRaw.Revision"
    OUTPUT_VARIABLE CYBERPUNK_2077_FILE_VERSION_PRIVATE OUTPUT_STRIP_TRAILING_WHITESPACE
  )
  set(CYBERPUNK_2077_FILE_VERSION_STR ${CYBERPUNK_2077_FILE_VERSION_MAJOR}.${CYBERPUNK_2077_FILE_VERSION_MINOR}.${CYBERPUNK_2077_FILE_VERSION_BUILD}.${CYBERPUNK_2077_FILE_VERSION_PRIVATE})

  message(STATUS "Game's FileVersion: ${CYBERPUNK_2077_FILE_VERSION_STR}")

  file(READ ${CMAKE_CURRENT_LIST_DIR}/GameVersions.json GAME_VERSIONS)
  string(JSON CYBERPUNK_2077_GAME_VERSION_STR ERROR_VARIABLE UNKNOWN_GAME_VERSION GET ${GAME_VERSIONS} ${CYBERPUNK_2077_FILE_VERSION_STR})
  if(NOT UNKNOWN_GAME_VERSION STREQUAL "NOTFOUND")
    string(JSON GAME_VERSIONS SET ${GAME_VERSIONS} ${CYBERPUNK_2077_FILE_VERSION_STR} "\"Unknown Game Version\"")
    file(WRITE ${CMAKE_CURRENT_LIST_DIR}/GameVersions.json ${GAME_VERSIONS})
    message(FATAL_ERROR "Unknown Game Version - Update red4ext.sdk/cmake/GameVersions.json")
  endif()
  message(STATUS "Game's Version: ${CYBERPUNK_2077_GAME_VERSION_STR}")
else()
  file(READ ${CMAKE_CURRENT_LIST_DIR}/GameVersions.json GAME_VERSIONS)
  string(JSON NUM_VERSIONS LENGTH ${GAME_VERSIONS})
  math(EXPR LAST_IDX "${NUM_VERSIONS} - 1")
  string(JSON CYBERPUNK_2077_FILE_VERSION_STR ERROR_VARIABLE UNKNOWN_GAME_VERSION MEMBER ${GAME_VERSIONS} ${LAST_IDX})
  string(JSON CYBERPUNK_2077_GAME_VERSION_STR ERROR_VARIABLE UNKNOWN_GAME_VERSION GET ${GAME_VERSIONS} ${CYBERPUNK_2077_FILE_VERSION_STR})

  string(REPLACE "." ";" CYBERPUNK_2077_FILE_VERSION_LIST ${CYBERPUNK_2077_FILE_VERSION_STR})
  list(GET CYBERPUNK_2077_FILE_VERSION_LIST 0 CYBERPUNK_2077_FILE_VERSION_MAJOR)
  list(GET CYBERPUNK_2077_FILE_VERSION_LIST 1 CYBERPUNK_2077_FILE_VERSION_MINOR)
  list(GET CYBERPUNK_2077_FILE_VERSION_LIST 2 CYBERPUNK_2077_FILE_VERSION_BUILD)
  list(GET CYBERPUNK_2077_FILE_VERSION_LIST 3 CYBERPUNK_2077_FILE_VERSION_PRIVATE)
  
  message(STATUS "Game's FileVersion: ${CYBERPUNK_2077_FILE_VERSION_STR}")
  message(STATUS "Game's Version: ${CYBERPUNK_2077_GAME_VERSION_STR}")
endif()